#!/bin/bash
#
# Diff dotfiles with system files

set -e

cd "$(dirname $0)"/..

# export source dotfiles directory to installers
export SRC_DIR=$(pwd)
export INSTALL_DIR=$HOME

diff_files() {
    colordiff "$INSTALL_DIR/$2" "$SRC_DIR/$1" || \
    echo -e "\e[0;31m$INSTALL_DIR/$2\e[0m and \e[34m$SRC_DIR/$1\e[0m differ"
}

export -f diff_files

# find the installers and run them iteratively
find . -name diff.sh | while read script ; do sh -c "$script" ; done
